"""Tests for the core project file path index generator."""

from __future__ import annotations

from pathlib import Path


def test_collect_index_entries_includes_core_directories_and_files_but_excludes_private_content(tmp_path):
    from scripts.update_file_path_index import collect_index_entries

    for path in [
        "src/data",
        "configs",
        "tests/fixtures/synthetic_dataset/train_images",
        "docs",
        "specs/001-feature",
        "scripts",
        "notebooks/.ipynb_checkpoints",
        "outputs/report",
        "artifacts/run",
        ".agents/cache",
    ]:
        (tmp_path / path).mkdir(parents=True)
    for path in [
        "README.md",
        "requirements.txt",
        "src/data/dataset.py",
        "configs/classifier.yaml",
        "tests/test_dataset.py",
        "docs/guide.md",
        "specs/001-feature/spec.md",
        "scripts/update_file_path_index.py",
        "notebooks/01_dataset_audit.ipynb",
        "outputs/report/metrics.json",
        "artifacts/run/model.pth",
        "tests/fixtures/synthetic_dataset/train_images/img_001.jpg",
        "notebooks/.ipynb_checkpoints/01-checkpoint.ipynb",
        ".agents/private.md",
    ]:
        (tmp_path / path).parent.mkdir(parents=True, exist_ok=True)
        (tmp_path / path).write_text("x", encoding="utf-8")

    entries = collect_index_entries(tmp_path)
    by_path = {entry.path.as_posix(): entry for entry in entries}

    assert by_path["src"].entry_type == "directory"
    assert by_path["src/data"].entry_type == "directory"
    assert by_path["src/data/dataset.py"].entry_type == "file"
    assert by_path["configs"].section == "Configuration"
    assert by_path["README.md"].section == "Repository Root"
    assert "outputs" not in by_path
    assert "artifacts" not in by_path
    assert ".agents" not in by_path
    assert "tests/fixtures/synthetic_dataset/train_images" not in by_path
    assert "tests/fixtures/synthetic_dataset/train_images/img_001.jpg" not in by_path
    assert "notebooks/.ipynb_checkpoints" not in by_path


def test_render_index_uses_stable_section_order_types_and_descriptions(tmp_path):
    from scripts.update_file_path_index import collect_index_entries, render_index

    (tmp_path / "src").mkdir()
    (tmp_path / "src" / "main.py").write_text("x", encoding="utf-8")
    (tmp_path / "README.md").write_text("x", encoding="utf-8")

    markdown = render_index(collect_index_entries(tmp_path), generated_at="2026-01-01 00:00:00 UTC")

    assert "Generated by `scripts/update_file_path_index.py`." in markdown
    assert "Excludes datasets, artifacts, outputs, model weights, caches, and private folders." in markdown
    assert markdown.index("## Repository Root") < markdown.index("## Source Code")
    assert "| Path | Type | Purpose |" in markdown
    assert "| `src/` | directory | Source package root. |" in markdown
    assert "| `src/main.py` | file | Python source file. |" in markdown
