"""Generate a project file path index for code navigation.

The index intentionally skips private datasets, generated artifacts, model
weights, caches, virtual environments, and local agent/tool state.
"""

from __future__ import annotations

import argparse
import os
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path


DEFAULT_OUTPUT = Path("docs/file-path-index.md")
EXCLUDED_DIRS = {
    ".git",
    ".pytest_cache",
    ".venv",
    "__pycache__",
    "1st-krones-vision-ai-challenge",
    "artifacts",
    "outputs",
    ".cursor",
    ".agents",
    ".gemini",
    ".opencode",
    ".ipynb_checkpoints",
    "datei",
    "test_images",
    "train_images",
}
EXCLUDED_SUFFIXES = {
    ".ckpt",
    ".engine",
    ".joblib",
    ".onnx",
    ".pth",
    ".pt",
    ".pkl",
    ".pyc",
    ".safetensors",
    ".weights",
    ".zip",
}
EXCLUDED_FILES = {"open-api.py", "opencode.json"}
SECTION_ORDER = [
    "Repository Root",
    "Configuration",
    "Source Code",
    "Tests",
    "Documentation",
    "Spec Kit Artifacts",
    "Scripts / Maintenance",
    "Notebooks",
    "Other Core Files",
]
ROOT_CORE_FILES = {
    ".gitignore",
    "AGENTS.md",
    "GEMINI.md",
    "README.md",
    "pyproject.toml",
    "requirements.txt",
    "setup.cfg",
    "setup.py",
}
ROOT_CORE_SUFFIXES = {".md", ".toml", ".txt", ".yaml", ".yml", ".ini", ".cfg"}


@dataclass(frozen=True)
class IndexEntry:
    path: Path
    entry_type: str
    section: str
    purpose: str


def collect_paths(root: Path) -> list[Path]:
    return [entry.path for entry in collect_index_entries(root) if entry.entry_type == "file"]


def collect_index_entries(root: Path) -> list[IndexEntry]:
    entries: list[IndexEntry] = []
    for current_root, dirnames, filenames in os.walk(root):
        current = Path(current_root)
        relative_dir = current.relative_to(root)
        dirnames[:] = [
            name
            for name in dirnames
            if not _is_excluded_path(relative_dir / name, is_dir=True)
        ]
        if relative_dir != Path(".") and _is_core_path(relative_dir, is_dir=True):
            entries.append(_make_entry(relative_dir, is_dir=True))
        for filename in filenames:
            path = current / filename
            relative = path.relative_to(root)
            if _is_excluded_path(relative, is_dir=False):
                continue
            if not _is_core_path(relative, is_dir=False):
                continue
            entries.append(_make_entry(relative, is_dir=False))
    return sorted(
        entries,
        key=lambda item: (SECTION_ORDER.index(item.section), item.path.as_posix().lower(), item.entry_type),
    )


def group_for(path: Path) -> str:
    first = path.parts[0] if path.parts else ""
    if len(path.parts) == 1 and path.name in ROOT_CORE_FILES:
        return "Repository Root"
    if first == "src":
        return "Source Code"
    if first == "tests":
        return "Tests"
    if first == "configs":
        return "Configuration"
    if first == "specs":
        return "Spec Kit Artifacts"
    if first == "docs":
        return "Documentation"
    if first == "notebooks" or path.suffix.lower() == ".ipynb":
        return "Notebooks"
    if first == "scripts":
        return "Scripts / Maintenance"
    if first == "specs" or first == ".specify":
        return "Spec Kit Artifacts"
    return "Other Core Files"


def render_index(entries: list[IndexEntry] | list[Path], generated_at: str | None = None) -> str:
    normalized_entries = [_make_entry(path, is_dir=False) if isinstance(path, Path) else path for path in entries]
    now = generated_at or datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    lines = [
        "# Project File Path Index",
        "",
        f"Generated: {now}",
        "",
        "Generated by `scripts/update_file_path_index.py`.",
        "",
        "Excludes datasets, artifacts, outputs, model weights, caches, and private folders.",
        "",
        "Refresh command:",
        "",
        "```powershell",
        "python scripts/update_file_path_index.py",
        "```",
        "",
    ]
    groups: dict[str, list[IndexEntry]] = {}
    for entry in normalized_entries:
        groups.setdefault(entry.section, []).append(entry)
    for group in SECTION_ORDER:
        if group not in groups:
            continue
        lines.append(f"## {group}")
        lines.append("")
        lines.append("| Path | Type | Purpose |")
        lines.append("| --- | --- | --- |")
        for entry in sorted(groups[group], key=lambda item: item.path.as_posix().lower()):
            path_text = entry.path.as_posix() + ("/" if entry.entry_type == "directory" else "")
            lines.append(f"| `{path_text}` | {entry.entry_type} | {entry.purpose} |")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _is_excluded_path(path: Path, *, is_dir: bool) -> bool:
    if any(part in EXCLUDED_DIRS for part in path.parts):
        return True
    if not is_dir and path.name in EXCLUDED_FILES:
        return True
    if not is_dir and path.suffix.lower() in EXCLUDED_SUFFIXES:
        return True
    return False


def _is_core_path(path: Path, *, is_dir: bool) -> bool:
    first = path.parts[0] if path.parts else ""
    if first in {"src", "configs", "tests", "docs", "specs", "scripts", "notebooks", ".specify"}:
        return True
    if len(path.parts) == 1:
        return is_dir is False and (path.name in ROOT_CORE_FILES or path.suffix.lower() in ROOT_CORE_SUFFIXES)
    return False


def _make_entry(path: Path, *, is_dir: bool) -> IndexEntry:
    return IndexEntry(
        path=path,
        entry_type="directory" if is_dir else "file",
        section=group_for(path),
        purpose=describe_path(path, is_dir=is_dir),
    )


def describe_path(path: Path, *, is_dir: bool) -> str:
    first = path.parts[0] if path.parts else ""
    if is_dir:
        descriptions = {
            "src": "Source package root.",
            "configs": "Configuration files.",
            "tests": "Automated tests and fixtures.",
            "docs": "Project documentation.",
            "specs": "Spec Kit feature artifacts.",
            "scripts": "Maintenance and utility scripts.",
            "notebooks": "Exploratory and workflow notebooks.",
            ".specify": "Spec Kit tooling metadata.",
        }
        if len(path.parts) == 1:
            return descriptions.get(first, "Core project directory.")
        return f"{descriptions.get(first, 'Core project directory.').rstrip('.')} subdirectory."
    if path.name == "README.md":
        return "Project overview and usage notes."
    if path.name == "requirements.txt":
        return "Python dependency list."
    if path.name == ".gitignore":
        return "Git ignore rules."
    if path.as_posix() == "configs/data_quality_audit.yaml":
        return "YAML configuration for the controlled data quality audit workflow."
    if path.as_posix() == "configs/data_quality_decision_lock.yaml":
        return "YAML configuration for the Spec 017 decision-lock workflow."
    if path.as_posix() == "configs/v2b_cleaned_replay_training.yaml":
        return "YAML configuration for the Spec 018 V2B-style cleaned replay training workflow."
    if path.as_posix() == "src/analysis/data_quality_audit.py":
        return "Python source file for the controlled data quality audit workflow."
    if path.as_posix() == "src/analysis/data_quality_decision_lock.py":
        return "Python source file for the Spec 017 decision-lock workflow."
    if path.as_posix() == "tests/test_data_quality_decision_lock.py":
        return "Pytest coverage for the Spec 017 decision-lock workflow."
    if path.as_posix() == "tests/test_v2b_cleaned_replay_training.py":
        return "Pytest coverage for the Spec 018 cleaned replay dry-run, training, and comparison workflow."
    if path.suffix == ".py":
        return "Python source file."
    if path.suffix in {".yaml", ".yml"}:
        return "YAML configuration or specification file."
    if path.suffix == ".md":
        return "Markdown documentation."
    if path.suffix == ".ipynb":
        return "Jupyter notebook."
    if path.suffix == ".json":
        return "JSON configuration or fixture file."
    if path.suffix == ".csv":
        return "CSV fixture or metadata file."
    if path.suffix == ".toml":
        return "TOML project configuration."
    return "Core project file."


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate docs/file-path-index.md")
    parser.add_argument("--root", type=Path, default=Path.cwd())
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    root = args.root.resolve()
    output = args.output if args.output.is_absolute() else root / args.output
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render_index(collect_index_entries(root)), encoding="utf-8")
    print(f"Wrote {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
